### ISSUE TITLE
More clear error message: "invalid map terminator"

### ISSUE THREAD

**Issue by koppor** [Shishqa/totosca#25]
I am testing the tool with https://github.com/frankakn/cloud-native-deployment/tree/main/DeploymentOptions

```console
$ toto check TeaStore-PaaS-Beanstalk.yaml
Error:
     ╭─[file:///C:/git-repositories/tosca/cloud-native-deployment/DeploymentOptions/TeaStore-PaaS-Beanstalk.yaml:193:20]
     │
 193 │       requirements:
     │                    ┬
     │                    ╰── invalid map terminator
─────╯
Error: "validation failed"
```

I checked https://docs.oasis-open.org/tosca/TOSCA/v2.0/csd06/TOSCA-v2.0-csd06.html#71-node-type, and I think, this is valid YAML, but I am not a YAML expert.

**Comment by Shishqa** [comment]
Hi! Thank you for the interest in `totosca` and sorry for the delayed reply

I was able to reproduce the bug by cloning the repository you provided:
![image](https://github.com/user-attachments/assets/e46114f1-cc27-44b8-8336-f2d0ea335169)

The original error message originates in the [yaml-peg-rs](https://github.com/KmolYuan/yaml-peg-rs/tree/main) crate [here](https://github.com/KmolYuan/yaml-peg-rs/blob/fe16e533232c7a8d52a0d82dfef0bdfa42a52f32/src/parser/mod.rs#L446), so I reported the issue https://github.com/KmolYuan/yaml-peg-rs/issues/14

To fix your issue you can enable auto whitespace trimming (e.g. in vscode https://stackoverflow.com/questions/30884131/remove-trailing-spaces-automatically-or-with-a-shortcut)

**Comment by Shishqa** [comment]
@koppor, The issue should be resolved now. Feel free to reopen this issue if not
